// noinspection JSUnusedGlobalSymbols
export enum PermissionEnum {
    // LED
    MAINTENANCE_MAKER = 'OPRISK_LED_MAINTENANCE_MAKER',
    MAINTENANCE_APPROVER = 'OPRISK_LED_MAINTENANCE_APPROVER',
    // REGISTRATION_MAKER = 'OPRISK_LED_REGISTRATION_MAKER',
    // REGISTRATION_CHECKER = 'OPRISK_LED_REGISTRATION_CHECKER',
    // REGISTRATION_APPROVER = 'OPRISK_LED_REGISTRATION_APPROVER',
    // REGISTRATION_APPROVER_MAKER = 'OPRISK_LED_REGISTRATION_APPROVER_MAKER',
    // MONITORING_MAKER = 'OPRISK_LED_MONITORING_MAKER',
    // MONITORING_APPROVER = 'OPRISK_LED_MONITORING_APPROVER',

    // KRI
    MAINTENANCE_RCSA_RISK_ADMIN = 'KRI_MAINTENANCE_RCSA_RISK_ADMIN',
    MAINTENANCE_RCSA_SUPERVISOR_RISK_ADMIN = 'KRI_MAINTENANCE_RCSA_SUPERVISOR_RISK_ADMIN',
    // HEADQUARTER_DEPTH_HEAD = 'KRI_HEADQUARTERS_DEPTH_HEAD',
    // HEADQUARTER_DCOR_HEAD = 'KRI_HEADQUARTERS_DCOR_HEAD',
    // HEADQUARTER_GROUP_HEAD = 'KRI_HEADQUARTERS_GROUP_HEAD',
    // HEADQUARTER_SORH = 'KRI_HEADQUARTERS_SORH',
    // NETWORK_BRANCH = 'KRI_NETWORKS_BRANCH',
    // NETWORK_AOSM = 'KRI_NETWORKS_AOSM',
    // NETWORK_SEGMENT_OFFICERS = 'KRI_NETWORKS_SEGMENT_OFFICERS',
    // NETWORK_AREA_SEGMENTS_MANAGER = 'KRI_NETWORKS_AREA_SEGMENTS_MANAGER',
    // NETWORK_ABCS = 'KRI_NETWORKS_ABCS',
    // NETWORK_AREA_MANAGER = 'KRI_NETWORKS_AREA_MANAGER',
    // NETWORK_OPERATION_DEPUTY = 'KRI_NETWORKS_OPERATION_DEPUTY',
    // NETWORK_RBCM = 'KRI_NETWORKS_RBCM',
    // NETWORK_RCEO = 'KRI_NETWORKS_RCEO',
    // NETWORK_SORH = 'KRI_NETWORKS_SORH',

    // RCSA
    RCSA_MAINTENANCE_RCSA_RISK_ADMIN = 'RCSA_MAINTENANCE_RCSA_RISK_ADMIN',
    RCSA_MAINTENANCE_RCSA_SUPERVISOR_RISK_ADMIN = 'RCSA_MAINTENANCE_RCSA_SUPERVISOR_RISK_ADMIN',
    // RCSA_HEADQUARTERS_DEPTH_HEAD = 'RCSA_HEADQUARTERS_DEPTH_HEAD',
    // RCSA_HEADQUARTERS_DCOR_HEAD = 'RCSA_HEADQUARTERS_DCOR_HEAD',
    // RCSA_HEADQUARTERS_SORH = 'RCSA_HEADQUARTERS_SORH',
    // RCSA_HEADQUARTERS_GROUP_HEAD = 'RCSA_HEADQUARTERS_GROUP_HEAD',
    // RCSA_NETWORKS_BRANCH = 'RCSA_NETWORKS_BRANCH',
    // RCSA_NETWORKS_AOSM = 'RCSA_NETWORKS_AOSM',
    // RCSA_NETWORKS_SEGMENT_OFFICERS = 'RCSA_NETWORKS_SEGMENT_OFFICERS',
    // RCSA_NETWORKS_AREA_SEGMENTS_MANAGER = 'RCSA_NETWORKS_AREA_SEGMENTS_MANAGER',
    // RCSA_NETWORKS_ABCS = 'RCSA_NETWORKS_ABCS',
    // RCSA_NETWORKS_AREA_MANAGER = 'RCSA_NETWORKS_AREA_MANAGER',
    // RCSA_NETWORKS_OPERATION_DEPUTY = 'RCSA_NETWORKS_OPERATION_DEPUTY',
    // RCSA_NETWORKS_RBCM = 'RCSA_NETWORKS_RBCM',
    // RCSA_NETWORKS_SORH = 'RCSA_NETWORKS_SORH',
    // RCSA_NETWORKS_RCEO = 'RCSA_NETWORKS_RCEO',

    // IAM

    // CT
    CT_MAINTENANCE_RSCA_RISK_ADMIN = 'CT_MAINTENANCE_RSCA_RISK_ADMIN',
    CT_MAINTENANCE_RSCA_SUPERVISOR_RISK_ADMIN = 'CT_MAINTENANCE_RSCA_SUPERVISOR_RISK_ADMIN',
    // CT_HEADQUARTER_CT_SUPERVISOR_ABC = 'CT_HEADQUARTER_CT_SUPERVISOR_ABC',
    // CT_HEADQUARTER_CT_RBC_MANAGER = 'CT_HEADQUARTER_CT_RBC_MANAGER',
    // CT_HEADQUARTER_CT_SORH = 'CT_HEADQUARTER_CT_SORH',
    // CT_NETWORK_CT_DCOR_OFFICER = 'CT_NETWORK_CT_DCOR_OFFICER',
    // CT_NETWORK_CT_DCOR_HEAD = 'CT_NETWORK_CT_DCOR_HEAD',
    // CT_NETWORK_CT_DCOR_SORH = 'CT_NETWORK_CT_DCOR_SORH',
}
